# Generated by Django 5.1.7 on 2025-04-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projetos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApoioContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=20)),
                ('relacao', models.CharField(choices=[('familia', 'Família'), ('cuidador', 'Cuidador'), ('vizinhos', 'Vizinhos'), ('emergencia', 'Serviços de Emergência')], max_length=20)),
            ],
        ),
    ]
