# Generated by Django 5.1.7 on 2025-04-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa_id', models.IntegerField()),
                ('glp', models.IntegerField()),
                ('co2', models.IntegerField()),
                ('temperatura', models.FloatField()),
                ('posicao', models.CharField(max_length=20)),
                ('saturacao', models.IntegerField()),
                ('localizacao', models.CharField(max_length=50)),
            ],
        ),
    ]
