# Generated by Django 5.1.7 on 2025-05-03 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projetos', '0003_perfil_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='apoiocontato',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='Projetos.perfil'),
        ),
    ]
